### ISSUE TITLE
Allow for difficulty markings (e.g. [10h], [10m], [10e]) in bonus part point values

### ISSUE THREAD

**Issue by ryanrosenberg** [alopezlago/YetAnotherPacketParser#20]
Right now YAPP does not recognize bonus parts where there is a difficulty marking inside the bonus part; ideally YAPP would parse this difficulty marking and include it in the output, or at least ignore it.

**Comment by alopezlago** [comment]
Interesting, I haven't seen this format before. Do we always expect to be e/m/h, or do we just expect it to be a single letter?

**Comment by ryanrosenberg** [comment]
I'd expect it to generally be e/m/h, yeah -- I can't think of any tournaments in the past 5-10 years that diverged from that schematic.

**Comment by alopezlago** [comment]
Okay. By the way, do you have an example packet that uses this format? I'd like to make sure that I can validate the parser against a real-world example

**Comment by ryanrosenberg** [comment]
Sure, here's a Spring Novice packet
[Packet 1 (3).docx](https://github.com/alopezlago/YetAnotherPacketParser/files/6767441/Packet.1.3.docx)

**Comment by alopezlago** [comment]
Thanks. I have something working where it ignores the values, though I want to see if I can keep the difficulty markings in the output.
