### ISSUE TITLE
Fill out bold/italic/underline for question text words

### ISSUE THREAD

**Issue by alopezlago** [alopezlago/YetAnotherPacketParser#44]
Instead of allowing words to have different formatting in different parts of the word (e.g. first part bolded, second part regular) for the question text, we should make the formatting consistent per word. This should simplify any logic for parsing things in the question text, because we know that the formatting won't change between words.

Note that this doesn't apply to the answerline text because underline/bold can be used to show which part of a word is required.

**Comment by hftf** [comment]
I don't think this holds in practice: examples include English plurals of foreign words (*raga*s, *koan*s), mathematical symbols (2*n*, *n*th, **R**<sup>*n*</sup>), scientific terms (*Eco*RI).

**Comment by alopezlago** [comment]
That's too bad, I'll close this then.
