### ISSUE TITLE
YAPP ignores subscripts/superscripts, causing misleading required parts of answer

### ISSUE THREAD

**Issue by hftf** [alopezlago/YetAnotherPacketParser#50]
Here are 4 examples just from two adjacent packets:
1. The `2` should be underlined in [Packet 8, bonus 13](https://files.quizbowlpackets.com/2964/Packet%2008.pdf#page=10)
Packet: <b><ins>N<sub>2</sub>O</ins></b>
YAPP:   <b><ins>N</ins>2<ins>O</b></ins> (“N-2-O”) [or <b><u>nitrous oxide</b></u>] ⇐ `<b><u>N</u>2<u>O</b></u> (“N-2-O”) [or <b><u>nitrous oxide</b></u>]`
2. But for some reason the `2` is underlined correctly here
Packet: <b><ins>NO<sub>2</sub></ins></b>
YAPP:   <b><ins>NOx</b></ins> (“nox”) compounds [accept <b><ins>NO</b></ins> AND <b><ins>NO2</b></ins> ⇐ `<b><u>NOx</b></u> (“nox”) compounds [accept <b><u>NO</b></u> AND <b><u>NO2</b></u>`
   > <img width="730" height="120" alt="Screen Shot 2024-03-04 at 05 52 57" src="https://github.com/alopezlago/YetAnotherPacketParser/assets/312957/99d4ed83-ba2b-4045-8f4d-53981ff0d9ec">
3. The `2` should be underlined in [Packet 7, bonus 9](https://files.quizbowlpackets.com/2964/Packet%2007.pdf#page=9)
Packet: <b><ins>CO<sub>2</sub></ins></b>
YAPP:   <b><ins>CO</ins>2</b> (“C-O-2”) [or <b><u>carbon dioxide</b></u>] ⇐ `<b><u>CO</u>2</b> (“C-O-2”) [or <b><u>carbon dioxide</b></u>]`
4. The `2` should be underlined
Packet: <b><ins>H<sub>2</sub></ins></b>
YAPP:   <b><ins>hydrogen</b></ins> [or <b><ins>H</ins>2 </b>(“H-2”)] ⇐ `<b><u>hydrogen</b></u> [or <b><u>H</u>2 </b>(“H-2”)]`
   > <img height="182" alt="Screen Shot 2024-03-04 at 06 21 15" src="https://github.com/alopezlago/YetAnotherPacketParser/assets/312957/5f4fa73b-4d15-42bd-a05c-af5d82b0e86f">

For what it's worth, I have strongly recommended against any use at all of subscripts/superscripts in quizbowl packets for many years, and this issue demonstrates two of the reasons: they mislead about the required parts of answers and interact poorly with underlining, and technology is often not designed to handle them correctly. Like #49, this issue should be classed high severity.

Note also that invalid tag nesting is produced throughout: `<b><u>hydrogen</b></u>`. Can file a separate issue for this if you want, but it's possibly the same root issue. See:
https://github.com/alopezlago/YetAnotherPacketParser/blob/00c6f583c552aa4d1112c4871148468110ad6957/YetAnotherPacketParser/YetAnotherPacketParser/Compiler/Html/HtmlCompiler.cs#L103-L156

**Comment by alopezlago** [comment]
I've been meaning to file a bug and fix super/subscript issues for a while and never got around to it. We have to read the super/sub script tags from docx and from HTML to know that it exists, persist that information, and then write it later (and have MODAQ know about super and subscript tags). I don't really care that much about mixing the tag ordering that much, but I could fix it separately.

**Comment by alopezlago** [comment]
This will be fixed in the next version.
